ecosoft-odoo/cmo_generic

sale_invoice_line_percentage/models/sale_v7.py
sale_invoice_plan/models/sale.py

Fix wrong invoice by percentage creating.

[FIX] invoice line percentage

---

jasper_reports/jasper_report.py

[IMP] Check No Data

---

l10n_th_tax_report/report/account_tax_report.jrxml
l10n_th_tax_report/report/account_tax_report.py

P'Nuii please merge krub.
Ref issue >> http://128.199.123.133:10083/issues/885

[IMP] Change partner name to Cancelled for doctype = sale

---

l10n_th_tax_report/report/account_tax_report.jrxml

[IMP] Cancel inv not show in purchase tax report

---

l10n_th_account/wizard/print_wht_cert_wizard.py

P'Nuii please merge.
Ref issue >> http://128.199.123.133:10083/issues/906

[IMP] Add parameter to report

---

l10n_th_account/wizard/print_wht_cert_wizard.py

P'Nuii please review krub
Ref issue >> http://128.199.123.133:10083/issues/906

[IMP] Add rate in WHT Cert Form

---

l10n_th_fields/views/account_invoice_view.xml

P'Nuii please review krub.
Ref issue >> http://128.199.123.133:10083/issues/924

[IMP] Add oe_button_box

---

l10n_th_account_pnd_form/report/report_pnd53_form_xls.jrxml

P'Nuii please merge krub.
Ref issue >> http://128.199.123.133:10083/issues/930

[IMP] Add pnd53 xls

---

account_bank_payment/views/account_bank_payment_view.xml
account_bank_receipt/views/account_bank_receipt_view.xml

[IMP] Add cancel button to state draft

---

account_bank_payment/views/account_bank_payment_view.xml
account_bank_receipt/views/account_bank_receipt_view.xml

[IMP] Adjust context bank intransit

---

account_cancel_reversal/__openerp__.py
account_cancel_reversal/models/__init__.py
account_cancel_reversal/models/account_bank_payment.py
account_cancel_reversal/views/account_bank_payment_view.xml

P'Nuii please review krub.
Ref issue >> http://128.199.123.133:10083/issues/942

[IMP] Adjust cancel account bank payment

---

account_financial_report/model/account_financial_report.py
account_financial_report/report/parser.py
account_financial_report/view/account_financial_report_view.xml
account_financial_report/wizard/wizard.py

P'Nuii please review krub
Ref issue >> http://128.199.123.133:10083/issues/911

[IMP] Update account_financial_report

---

account_supplier_billing/models/account_voucher.py
account_supplier_billing/views/supplier_billing.xml

P'Nuii please review and merge krub.
Ref issue >> http://128.199.123.133:10083/issues/966

[IMP] Add domain ('invoice_ids.state', 'not in', ('paid', 'cancel')) in supplier_billing_id

---

account_bank_receipt/models/account_voucher.py

P'Nuii please review and merge krub.
Ref issue >> http://128.199.123.133:10083/issues/961

[IMP] Default payment method of customer payment

---

account_supplier_billing/models/account_voucher.py
account_supplier_billing/views/supplier_billing.xml

[IMP] Remove domain invoice state from supplier_billing_id and remove search by number and partner

---

l10n_th_amount_text/all_docs.py

[IMP] Remove default = default out from super

---

meta_groups/__openerp__.py
meta_groups/security/ir.model.access.csv

[IMP] Add security file

---

account_pettycash/models/hr_expense.py

Objective
Set default pettycash_id when pay to is pettycash
http://128.199.123.133:10083/issues/960

[IMP] Add change default = 1 (Pay to)

---

account_financial_report_webkit/report/common_reports.py

http://128.199.123.133:10083/issues/1535

[IMP] Add superuser with general ledger report

---

account_financial_report_webkit/report/common_reports.py

issue >> http://128.199.123.133:10083/issues/1594

[FIX] Adjust sql where of analytic account

---

l10n_th_account_tax_detail/models/account_tax_detail.py

[IMP] Update account tax detail

---

l10n_th_account/models/account_wht_cert.py

แก้ไข type Integer -> Float กรณีหารแล้วมีเศษ แต่ระบบเดิมปัดเศษ ทำให้เมื่อออกรายงานทำให้ตัวเลขไม่ถูกต้อง

Change type Integer -> Float
